apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: boltz-pre-pulling
spec:
  selector:
    matchLabels:
      app: boltz-pre-pulling
  template:
    metadata:
      labels:
        app: boltz-pre-pulling
    spec:
      tolerations:
      - operator: "Exists"   # Run on all nodes, including tainted ones
      containers:
      - name: prepull
        image: ghcr.io/nebius-academy/boltz2-mk8s:latest
        command: ["sleep", "infinity"] # Keep running until manually deleted
      restartPolicy: Always
